USE [master]
GO

/****** Object:  Database [PruebaTecnicaJunior]    Script Date: 15/06/2024 10:31:00 p. m. ******/
CREATE DATABASE [PruebaTecnicaJunior]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaTecnicaJunior', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.CAMILO\MSSQL\DATA\PruebaTecnicaJunior.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PruebaTecnicaJunior_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.CAMILO\MSSQL\DATA\PruebaTecnicaJunior_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PruebaTecnicaJunior] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaTecnicaJunior].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PruebaTecnicaJunior] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET ARITHABORT OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET  MULTI_USER 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PruebaTecnicaJunior] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PruebaTecnicaJunior] SET  READ_WRITE 
GO

